apiVersion: v1
kind: ConfigMap
metadata:
  name: sleep-service-config
  labels:
    app: sleep-service
data:
  application-prod.yml: |
    spring:
      datasource:
        url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
      
      jpa:
        hibernate:
          ddl-auto: validate
        database: mysql
        database-platform: org.hibernate.dialect.MySQL8Dialect
        open-in-view: false
        show-sql: false
        properties:
          hibernate:
            format_sql: false
      
      data:
        mongodb:
          uri: mongodb://${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}
      
      redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        timeout: 2000ms
        lettuce:
          pool:
            max-active: 8
            max-idle: 8
            min-idle: 0
      
      kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
        consumer:
          group-id: sleep-service-group
          auto-offset-reset: earliest
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.apache.kafka.common.serialization.StringSerializer
      
      cache:
        type: redis
        redis:
          time-to-live: 600000
      
      security:
        jwt:
          secret: ${JWT_SECRET}
          access-token-expiration: 1800000
          refresh-token-expiration: 604800000
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics
      endpoint:
        health:
          show-details: when-authorized
      health:
        redis:
          enabled: true
        db:
          enabled: true
        mongo:
          enabled: true
    
    logging:
      level:
        com.project.sleep: INFO
        org.springframework.security: WARN
        org.hibernate.SQL: WARN
        org.hibernate.type.descriptor.sql.BasicBinder: WARN
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
      file:
        name: /app/logs/sleep-service.log
