# ArgoCD Values for Production
global:
  domain: argocd.local
  image:
    repository: quay.io/argoproj/argocd
    tag: v2.8.4
  imagePullPolicy: IfNotPresent

server:
  service:
    type: LoadBalancer
    servicePort: 80
  extraArgs:
    - --insecure
  config:
    url: http://argocd-server-lb.argocd.svc.cluster.local
    application.instanceLabelKey: argocd.argoproj.io/instance
    oidc.config: |
      name: OIDC
      issuer: https://oidc.example.com
      clientId: aaa
      clientSecret: $oidc.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups"]
      requestedIDTokenClaims: {"groups": {"essential": true}}
    repositories: |
      - type: git
        url: https://github.com/Octa-Cloud/user-service
        name: user-service
      - type: git
        url: https://github.com/Octa-Cloud/Infra
        name: infra

controller:
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

repoServer:
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

dex:
  enabled: false

redis:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
