apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: cm9vdA==
  password: cmxhcnVkcmIxMTk=
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  secret: S0l0RldNWm9rcGlTajZBQmk0MlhKcE5XYkJxVUo0VVQzbWhMclhrLy9JajI2VGdReTJCa2syS3JDa2Q0Y1FEbDhvRnNTWUg5R3IrK0xxcjJ3NkNZSm5RPT0=
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
type: Opaque
data:
  username: bW9uZy5oZWFsdGhAZ21haWwuY29t
  password: ZXluZXhmcnVmanlrdXRsdw==
---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-sa-key
type: Opaque
data:
  key.json: ""
