apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: YWRtaW4=  # base64 encoded 'admin'
  password: cGFzc3dvcmQ=  # base64 encoded 'password' - change this!
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  password: cGFzc3dvcmQ=  # base64 encoded 'password' - change this!
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  secret: eW91ci1qd3Qtc2VjcmV0LWtleS1oZXJl  # base64 encoded 'your-jwt-secret-key-here' - change this!
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
type: Opaque
data:
  username: eW91ci1lbWFpbEBleGFtcGxlLmNvbQ==  # base64 encoded 'your-email@example.com' - change this!
  password: eW91ci1lbWFpbC1wYXNzd29yZA==  # base64 encoded 'your-email-password' - change this!
---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-sa-key
type: Opaque
data:
  key.json: ""  # GCP Service Account key - add this!
