apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  secret: S0l0RldNWm9rcGlTajZBQmk0MlhKcE5XYkJxVUo0VVQzbWhMclhrLy9JajI2VGdReTJCa2syS3JDa2Q0Y1FEbDhvRnNTWUg5R3IrK0xxcjJ3NkNZSm5RPT0=  # base64 encoded JWT secret
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
type: Opaque
data:
  username: bW9uZy5oZWFsdGhAZ21haWwuY29t  # base64 encoded 'mong.health@gmail.com'
  password: ZXluZXhmcnVmank5a3V0bHc=  # base64 encoded 'eynexfrufjykutlw'
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ5b3VyLXJlZ2lzdHJ5LmNvbSI6eyJ1c2VybmFtZSI6InlvdXItdXNlcm5hbWUiLCJwYXNzd29yZCI6InlvdXItcGFzc3dvcmQiLCJhdXRoIjoiWVdSdGFXNDZNVEl6TkRVPSJ9fX0=  # base64 encoded docker config - change this!
