name: ArgoCD Sync

on:
  push:
    branches: [ main ]
    paths:
      - 'k8s-gcp/argocd/**'
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        description: 'Docker image tag to sync'
        required: true
        type: string
      ENVIRONMENT:
        description: 'Environment to sync (dev/prod)'
        required: false
        type: string
        default: 'dev'

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: asia-northeast3
  GKE_CLUSTER_NAME: microservices-cluster
  NAMESPACE: microservices
  ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}

jobs:
  argocd-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install GKE auth plugin
        run: gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Get GKE credentials
        run: |
          set -euo pipefail
          gcloud container clusters get-credentials "${GKE_CLUSTER_NAME}" --region "${GCP_REGION}" --project "${GCP_PROJECT_ID}"

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          rm argocd-linux-amd64
          argocd version --client

      # 🔎 80포트 엔드포인트만 잡고 --plaintext만 사용
      - name: Get ArgoCD server endpoint (port 80)
        run: |
          set -euo pipefail
          # argocd-server-lb 우선, 없으면 argocd-server
          IP="$(kubectl -n argocd get svc argocd-server-lb -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || true)"
          HOST="$(kubectl -n argocd get svc argocd-server-lb -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)"
          if [ -z "$IP$HOST" ]; then
            IP="$(kubectl -n argocd get svc argocd-server -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || true)"
            HOST="$(kubectl -n argocd get svc argocd-server -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)"
          fi
          ENDPOINT="${HOST:-$IP}"
          if [ -z "$ENDPOINT" ]; then echo "No external endpoint for Argo CD"; exit 1; fi

          echo "ARGOCD_SERVER=${ENDPOINT}:80" >> "$GITHUB_ENV"
          echo "ARGOCD_FLAGS=--insecure --grpc-web --plaintext" >> "$GITHUB_ENV"
          # 혹시 남아있을 수 있는 전역 옵션 제거
          unset ARGOCD_OPTS || true

          # 빠른 헬스 체크(실패해도 계속 진행)
          timeout 10s curl -sv "http://${ENDPOINT}:80/api/version" || true

      - name: Update Application with new image tag
        run: |
          set -euo pipefail
          ENV="${{ github.event.inputs.ENVIRONMENT || 'dev' }}"
          APP_NAME="user-service-${ENV}"
          TAG="${{ github.event.inputs.IMAGE_TAG }}"
          echo "SERVER=$ARGOCD_SERVER FLAGS=$ARGOCD_FLAGS APP=$APP_NAME TAG=$TAG"
          argocd $ARGOCD_FLAGS --server "$ARGOCD_SERVER" --auth-token "$ARGOCD_TOKEN" app set "${APP_NAME}" --helm-set image.tag="${TAG}"

      - name: Sync Application
        run: |
          set -euo pipefail
          ENV="${{ github.event.inputs.ENVIRONMENT || 'dev' }}"
          APP_NAME="user-service-${ENV}"
          # 네트워크 플럭스 대비 재시도
          for i in {1..3}; do
            if timeout 120s argocd $ARGOCD_FLAGS --server "$ARGOCD_SERVER" --auth-token "$ARGOCD_TOKEN" app sync "${APP_NAME}" --force -v; then
              break
            fi
            [ $i -eq 3 ] && exit 1
            sleep $((i*5))
          done

      - name: Wait for sync completion
        run: |
          set -euo pipefail
          ENV="${{ github.event.inputs.ENVIRONMENT || 'dev' }}"
          APP_NAME="user-service-${ENV}"
          argocd $ARGOCD_FLAGS --server "$ARGOCD_SERVER" --auth-token "$ARGOCD_TOKEN" app wait "${APP_NAME}" --timeout 300 -v

      - name: Get application status
        run: |
          set -euo pipefail
          ENV="${{ github.event.inputs.ENVIRONMENT || 'dev' }}"
          APP_NAME="user-service-${ENV}"
          argocd $ARGOCD_FLAGS --server "$ARGOCD_SERVER" --auth-token "$ARGOCD_TOKEN" app get "${APP_NAME}" -v
