name: Deploy to GCP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: asia-northeast3
  GKE_CLUSTER_NAME: microservices-cluster
  GKE_ZONE: asia-northeast3-a

jobs:
  deploy-k8s:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Install GKE auth plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet
        echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

    - name: Deploy Kubernetes manifests
      run: |
        set -euo pipefail
        # Get GKE credentials
        gcloud container clusters get-credentials "$GKE_CLUSTER_NAME" --region "$GCP_REGION" --project "$GCP_PROJECT_ID"

        # Ensure namespace exists
        kubectl get ns microservices >/dev/null 2>&1 || kubectl create namespace microservices

        # Apply infra secrets if present
        if [ -f infrastructure/k8s-gcp/infrastructure/secrets.yaml ]; then
          kubectl apply -f infrastructure/k8s-gcp/infrastructure/secrets.yaml -n microservices
        else
          echo "::warning::infrastructure/k8s-gcp/infrastructure/secrets.yaml not found, skipping"
        fi

        # Apply user-service manifests if directory exists
        if [ -d infrastructure/k8s-gcp/user-service ]; then
          kubectl apply -f infrastructure/k8s-gcp/user-service -n microservices
        else
          echo "::warning::infrastructure/k8s-gcp/user-service not found, skipping"
        fi

        # Apply sleep-service manifests if directory exists
        if [ -d infrastructure/k8s-gcp/sleep-service ]; then
          kubectl apply -f infrastructure/k8s-gcp/sleep-service -n microservices
        else
          echo "::warning::infrastructure/k8s-gcp/sleep-service not found, skipping"
        fi

  # build-and-push job removed: images are built in their own repos' CI
