name: Deploy to GCP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: asia-northeast3
  GKE_CLUSTER_NAME: microservices-cluster
  GKE_ZONE: asia-northeast3-a

jobs:
  deploy-k8s:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Deploy Kubernetes manifests
      run: |
        # Get GKE credentials
        gcloud container clusters get-credentials $GKE_CLUSTER_NAME --region $GCP_REGION --project $GCP_PROJECT_ID
        
        # Deploy infrastructure
        kubectl apply -f k8s-gcp/infrastructure/namespace.yaml
        kubectl apply -f k8s-gcp/infrastructure/secrets.yaml
        
        # Deploy services
        kubectl apply -f k8s-gcp/user-service/
        kubectl apply -f k8s-gcp/sleep-service/

  # build-and-push job removed: images are built in their own repos' CI
