name: Terraform Plan

on:
  pull_request:
    paths:
      - 'terraform-gcp/**'
    branches: [ main ]
  push:
    paths:
      - 'terraform-gcp/**'
    branches: [ main ]

env:
  TF_VERSION: '1.6.0'
  TF_WORKING_DIR: 'terraform-gcp/environments/production'
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  terraform-plan:
    name: 'Terraform Plan (GCP)'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud (SA key)
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}

    - name: Who am I (debug)
      run: |
        gcloud auth list
        gcloud config list account

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Format Check
      id: fmt
      run: terraform fmt -check
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Terraform Init
      id: init
      run: terraform init -input=false
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Comment PR
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        header: terraform-plan
        message: |
          ```terraform
          ${{ steps.plan.outputs.stdout }}
          ```
