name: Terraform Apply

on:
  push:
    paths:
      - 'terraform-gcp/**'
    branches: [ main ]
  workflow_dispatch: {}

env:
  TF_VERSION: '1.6.0'
  TF_WORKING_DIR: 'terraform-gcp/environments/production'
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  terraform-apply:
    name: 'Terraform Apply (GCP)'
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud (SA key)
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}

    - name: Who am I (debug)
      run: |
        gcloud auth list
        gcloud config list account
        gcloud projects get-iam-policy ${GCP_PROJECT_ID} --flatten='bindings[].members' --filter="bindings.members:$(gcloud config get account)" --format='table(bindings.role)'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init -input=false
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Import existing resources (idempotent)
      run: |
        set -euo pipefail
        # Helper: try import only if not already in state
        tf_try_import() {
          addr="$1"; id="$2"
          if terraform state show "$addr" > /dev/null 2>&1; then
            echo "State already has $addr"
          else
            echo "Importing $addr -> $id"
            terraform import "$addr" "$id" || true
          fi
        }

        # VPC network
        tf_try_import 'module.vpc.google_compute_network.main' 'projects/${{ env.GCP_PROJECT_ID }}/global/networks/microservices'

        # Redis (Memorystore)
        tf_try_import 'google_redis_instance.redis' 'projects/${{ env.GCP_PROJECT_ID }}/locations/asia-northeast3/instances/microservices-redis'

        # Pub/Sub topics
        tf_try_import 'google_pubsub_topic.user_events' 'projects/${{ env.GCP_PROJECT_ID }}/topics/user-events'
        tf_try_import 'google_pubsub_topic.sleep_events' 'projects/${{ env.GCP_PROJECT_ID }}/topics/sleep-events'

        # Service Account
        tf_try_import 'google_service_account.gke_sa' 'projects/${{ env.GCP_PROJECT_ID }}/serviceAccounts/microservices-gke-sa@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

        # Firestore default DB (already exists normally)
        tf_try_import 'google_firestore_database.firestore' 'projects/${{ env.GCP_PROJECT_ID }}/databases/(default)'
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Refresh state from real infra (no changes)
      run: |
        terraform apply -refresh-only -auto-approve
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Terraform Plan
      run: terraform plan -no-color -input=false -out=tfplan
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Outputs
      run: |
        echo "Cluster Name:" && terraform output -raw cluster_name || true
        echo "Cluster Endpoint:" && terraform output -raw cluster_endpoint || true
      working-directory: ${{ env.TF_WORKING_DIR }}
