name: Terraform Apply

on:
  push:
    paths:
      - 'terraform-gcp/**'
    branches: [ main ]
  workflow_dispatch: {}

env:
  TF_VERSION: '1.6.0'
  TF_WORKING_DIR: 'terraform-gcp/environments/production'
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  terraform-apply:
    name: 'Terraform Apply (GCP)'
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud (SA key)
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}

    - name: Who am I (debug)
      run: |
        gcloud auth list
        gcloud config list account
        gcloud projects get-iam-policy ${GCP_PROJECT_ID} --flatten='bindings[].members' --filter="bindings.members:$(gcloud config get account)" --format='table(bindings.role)'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init -input=false
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Terraform Plan
      run: terraform plan -no-color -input=false -out=tfplan
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Outputs
      run: |
        echo "Cluster Name:" && terraform output -raw cluster_name || true
        echo "Cluster Endpoint:" && terraform output -raw cluster_endpoint || true
      working-directory: ${{ env.TF_WORKING_DIR }}
